### ISSUE TITLE
GUI players not found

### ISSUE THREAD

**Issue by HuaDeity** [vitorgalvao/play-address-workflow#1]
### Workflow version

2024.1

### Alfred version

5.5 [2257]

### macOS version

Sonoma 14.4

### Debugger output

```alfred_debugger
[13:26:40.715] STDERR: Play Address[Run Script] Unable to find application named 'com.colliderli.iina'
```

### More details

The issue is related to the script below, which uses the `open` command to open a media URL with one of several GUI players:
```
# GUI players
for gui in 'io.mpv' 'com.vitorgalvao.mpvdummy' 'com.colliderli.iina' 'org.videolan.vlc'
do
  if [[ "$(/usr/bin/mdfind kMDItemCFBundleIdentifier = "${gui}")" ]]
  then
    open -na "${gui}" --args "${url}"
    exit 0
  fi
done
```

I tested the command `open -na com.colliderli.iina` in Terminal, but it resulted in the same error. It appears that the `open` command on macOS 14.4 behaves differently.

According to the usage information for `open` displayed in Terminal on macOS 14.4:

- `-a`: Opens with the specified application.
- `-b`: Opens with the specified application bundle identifier.

To fix this issue, two possible workarounds are suggested:

1. Change 
`open -na "${gui}" --args "${url}"` 
to 
`open -nb "${gui}" --args "${url}"`.

2. Add a variable `app_path` as follows:
```
# GUI players
for gui in 'io.mpv' 'com.vitorgalvao.mpvdummy' 'com.colliderli.iina' 'org.videolan.vlc'
do
  app_path=$(/usr/bin/mdfind kMDItemCFBundleIdentifier = "${gui}")
  if [[ "${app_path}" ]]
  then
    open -na "${app_path}" --args "${url}"
    exit 0
  fi
done
```

**Comment by vitorgalvao** [comment]
Thank you. Fixed and new version has been released.
